create table members (
    id bigint generated by default as identity primary key,
    public_id uuid not null,
    auth_subject varchar(255) not null,
    password_hash varchar(255) not null,
    display_name varchar(255),
    status varchar(20) not null default 'ACTIVE',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint members_public_id_uq unique (public_id),
    constraint members_auth_subject_uq unique (auth_subject),
    constraint members_status_chk check (status in ('ACTIVE', 'INACTIVE', 'ANONYMIZED'))
);
