create table booking_slots (
    id bigint generated by default as identity primary key,
    public_id uuid not null,
    booking_provider_id bigint not null references booking_providers (id),
    starts_at timestamp with time zone not null,
    ends_at timestamp with time zone not null,
    total_capacity integer not null,
    available_capacity integer not null,
    status varchar(20) not null default 'AVAILABLE',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint booking_slots_public_id_uq unique (public_id),
    constraint booking_slots_total_capacity_chk check (total_capacity > 0),
    constraint booking_slots_available_capacity_chk check (available_capacity >= 0 and available_capacity <= total_capacity),
    constraint booking_slots_ends_after_starts_chk check (ends_at > starts_at),
    constraint booking_slots_status_chk check (status in ('AVAILABLE', 'CLOSED', 'FULLY_BOOKED')),
    constraint booking_slots_provider_starts_uq unique (booking_provider_id, starts_at)
);

create index booking_slots_provider_date_idx
    on booking_slots (booking_provider_id, starts_at);
