create table hold_requests (
    id bigint generated by default as identity primary key,
    public_id uuid not null,
    member_id bigint not null references members (id),
    booking_slot_id bigint not null references booking_slots (id),
    party_size integer not null,
    status varchar(20) not null default 'PENDING',
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint hold_requests_public_id_uq unique (public_id),
    constraint hold_requests_party_size_chk check (party_size > 0),
    constraint hold_requests_status_chk check (status in ('PENDING', 'ACTIVE', 'FAILED', 'EXPIRED'))
);

create index hold_requests_member_idx on hold_requests (member_id);
create index hold_requests_slot_idx on hold_requests (booking_slot_id);
